kata 6
RTXVader/nc-news pull request #7
Opened 2023-06-29 15:30 UTC by RTXVader

2023-06-29 15:33 UTC, yalicee requested changes
Add these tests please:

- Status 200, valid ID, but has no comments responds with an empty array of comments
- Status 400, invalid ID, e.g. string of "not-an-id"
- Status 404, non existent ID, e.g. 0 or 9999

2023-06-29 15:33 UTC, yalicee commented on __tests__/app.test.js
> +        });
you can just combine these all to 1 test. Also if you use a forEach then you know its an array so first test is redundant.

2023-06-30 09:00 UTC, yalicee approved these changes
Make minor changes before you merge?

2023-06-30 09:00 UTC, yalicee commented on __tests__/app.test.js
> +
Test for empty array as well

2023-06-30 09:00 UTC, yalicee commented on modele/app.model.js
> +    const articleExists = rows[0].exists;
What is the .exists? Is it a property on the article object? Do you need it?

2023-06-30 09:03 UTC, RTXVader commented on modele/app.model.js
> +    const articleExists = rows[0].exists;
I think so its the boolean outcome of the article query to see if the article id belongs to an article

2023-06-30 09:05 UTC, RTXVader commented on __tests__/app.test.js
> +
is that for the 200: valid id but no comments respond with an empty array of comments test

2023-06-30 09:13 UTC, yalicee commented on __tests__/app.test.js
> +
Ye

2023-06-30 09:14 UTC, RTXVader commented on __tests__/app.test.js
> +
didn't I do it on line 177 with expect(comments).toHaveLength(0)

2023-06-30 09:31 UTC, merged